// Extension de l'application : unités par article et historique détaillé.
data.products.forEach(p=>{if(!p.unit)p.unit='pièce'});
function unit(n,u){return `${Number(n).toLocaleString('fr-FR',{maximumFractionDigits:3})} ${u||'pièce'}`}
function sale(){return `<div class="grid sale-grid"><section class="card"><h3>Articles de la vente</h3><div class="tools"><input class="search" placeholder="Rechercher un article..." oninput="productSearch(this.value)"><button class="secondary" onclick="showProducts()">+ Ajouter article</button></div><div id="productPicker"></div><table><thead><tr><th>Article</th><th>Stock disponible</th><th>Quantité vendue</th><th>Prix / unité</th><th>Total article</th></tr></thead><tbody>${cart.length?cart.map((x,i)=>`<tr><td><strong>${x.name}</strong></td><td>${unit(x.stock,x.unit)}</td><td><input style="width:65px" type="number" min="0.001" step="0.001" value="${x.qty}" onchange="setQty(${i},this.value)"> ${x.unit}</td><td>${money(x.price)} / ${x.unit}</td><td><strong>${money(x.price*x.qty)}</strong></td></tr>`).join(''):`<tr><td colspan="5" class="empty">Ajoutez des articles pour commencer la vente.</td></tr>`}</tbody></table></section>${summary()}</div>`}
function showProducts(q=''){let list=data.products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase()));productPicker.innerHTML=`<div class="card" style="padding:10px;margin-bottom:12px">${list.map(p=>`<button class="secondary" style="margin:3px" onclick="add(${p.id})">${p.name} · ${money(p.price)}/${p.unit} · ${unit(p.stock,p.unit)}</button>`).join('')}</div>`}
function setQty(i,v){let q=Number(v);if(!q||q<=0||q>cart[i].stock)return toast('Quantité invalide ou stock insuffisant');cart[i].qty=q;go('vente')}
function completeSale(){let total=cart.reduce((s,x)=>s+x.price*x.qty,0),received=+paid.value||0;if(!cart.length)return toast('Ajoutez au moins un article');if(received<total)return toast('Montant reçu insuffisant');let items=cart.map(x=>{let p=data.products.find(a=>a.id===x.id),before=p.stock;p.stock-=x.qty;return {...x,stockBefore:before,stockRemaining:p.stock}});data.sales.unshift({id:'V-'+Date.now().toString().slice(-6),date:new Date().toLocaleString('fr-FR'),cashier:user.name,items,total,paid:received,change:received-total,status:'Validée'});save();cart=[];toast('Vente enregistrée');go('mesventes')}
function salesRows(list,canCancel){return list.length?list.map(s=>`<tr><td><strong>${s.id}</strong><br><span class="stock">${s.date}</span></td><td>${s.cashier}</td><td>${s.items.map(i=>`${i.name} : ${unit(i.qty,i.unit)}`).join('<br>')}</td><td><strong>${money(s.total)}</strong></td><td><span class="pill ${s.status==='Annulée'?'red':''}">${s.status}</span></td><td><button class="secondary" onclick="saleDetail('${s.id}')">Détail</button>${canCancel&&s.status==='Validée'?` <button class="danger" onclick="cancelSale('${s.id}')">Annuler</button>`:''}</td></tr>`).join(''):`<tr><td colspan="6" class="empty">Aucune vente enregistrée.</td></tr>`}
function saleDetail(id){let s=data.sales.find(x=>x.id===id);modal(`<h2>Vente ${s.id}</h2><p>${s.date} · ${s.cashier}</p><table><thead><tr><th>Article</th><th>Avant</th><th>Vendu</th><th>Restant</th><th>Total</th></tr></thead><tbody>${s.items.map(i=>`<tr><td>${i.name}<br><span class="stock">${money(i.price)}/${i.unit||'pièce'}</span></td><td>${unit(i.stockBefore,i.unit)}</td><td>${unit(i.qty,i.unit)}</td><td>${unit(i.stockRemaining,i.unit)}</td><td>${money(i.price*i.qty)}</td></tr>`).join('')}</tbody></table><p><strong>Total : ${money(s.total)}</strong><br>Espèces reçues : ${money(s.paid)} · Monnaie : ${money(s.change)}</p><div class="actions"><button class="primary" onclick="closeModal()">Fermer</button></div>`)}
function stock(){return `<section class="card"><h3>Disponibilité des articles</h3><table><thead><tr><th>Article</th><th>Catégorie</th><th>Unité</th><th>Quantité disponible</th><th>Prix actuel</th></tr></thead><tbody>${data.products.map(p=>`<tr><td><strong>${p.name}</strong></td><td>${p.cat}</td><td>${p.unit}</td><td>${unit(p.stock,p.unit)}</td><td>${money(p.price)} / ${p.unit}</td></tr>`).join('')}</tbody></table></section>`}
